//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace muachung.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Advert
    {
        public int AdvertId { get; set; }

        [Display(Name = "Tên sản phẩm")]
        public string Title { get; set; }

        [Display(Name = "Địa chỉ cụ thể")]
        public string AdvertName { get; set; }

        [Display(Name = "Ảnh sản phẩm 1")]
        public string Images1 { get; set; }

        [Display(Name = "Ảnh sản phẩm 2")]
        public string Images2 { get; set; }

        [Display(Name = "Ảnh sản phẩm 3")]
        public string Images3 { get; set; }

        [Display(Name = "Giá (gốc)")]
        [DisplayFormat(DataFormatString = "{0:N0}")]
        public decimal Cost { get; set; }

        [Display(Name = "Giá (hạ)")]
        [DisplayFormat(DataFormatString = "{0:N0}")]
        public decimal CostSale { get; set; }

        [Display(Name = "Mô tả sản phẩm")]
        public string AdvertContent { get; set; }
        public Nullable<int> Views { get; set; }

        [Display(Name = "Vùng/Miền")]
        public string Address { get; set; }
        public bool Deleted { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        public virtual User User { get; set; }
    }
}
