//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace muachung.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class muachungEntities : DbContext
    {
        public muachungEntities()
            : base("name=muachungEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Advert> Adverts { get; set; }
    
        public virtual ObjectResult<SP_GET_LIST_ORDER_Result> SP_GET_LIST_ORDER(string phone)
        {
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_LIST_ORDER_Result>("SP_GET_LIST_ORDER", phoneParameter);
        }
    
        public virtual ObjectResult<SP_GET_PRODUCTS_ALL_Result> SP_GET_PRODUCTS_ALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_PRODUCTS_ALL_Result>("SP_GET_PRODUCTS_ALL");
        }
    
        public virtual ObjectResult<SP_GET_PRODUCTS_DELETED_Result> SP_GET_PRODUCTS_DELETED()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_PRODUCTS_DELETED_Result>("SP_GET_PRODUCTS_DELETED");
        }
    
        public virtual ObjectResult<SP_GET_PRODUCTS_HOT_Result> SP_GET_PRODUCTS_HOT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_PRODUCTS_HOT_Result>("SP_GET_PRODUCTS_HOT");
        }
    
        public virtual ObjectResult<SP_GET_USERS_ALL_Result> SP_GET_USERS_ALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_USERS_ALL_Result>("SP_GET_USERS_ALL");
        }
    
        public virtual ObjectResult<SP_GET_USERS_DELETED_Result> SP_GET_USERS_DELETED()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_USERS_DELETED_Result>("SP_GET_USERS_DELETED");
        }
    
        public virtual int SP_UP_AMOUNT_LIST_ORDER(string phone, Nullable<int> amount)
        {
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UP_AMOUNT_LIST_ORDER", phoneParameter, amountParameter);
        }
    
        public virtual int SP_DELETE_FROM_CART(string phone, Nullable<int> id)
        {
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_FROM_CART", phoneParameter, idParameter);
        }
    
        public virtual ObjectResult<SP_GET_Adverts_RD2_Result> SP_GET_Adverts_RD2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_Adverts_RD2_Result>("SP_GET_Adverts_RD2");
        }
    }
}
