//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace muachung.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Product
    {
        public Product()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }

        [Display(Name = "Mã sản phẩm")]
        public string ProductId { get; set; }

        [Display(Name = "Tên sản phẩm")]
        public string Name { get; set; }

        [Display(Name = "Ảnh 1")]
        public string Images1 { get; set; }

        [Display(Name = "Ảnh 2")]
        public string Images2 { get; set; }

        [Display(Name = "Ảnh 3")]
        public string Images3 { get; set; }

        [Display(Name = "Giá (gốc)")]
        [DisplayFormat(DataFormatString = "{0:N0}")]
        public decimal Cost { get; set; }

        [Display(Name = "Giá (hạ)")]
        [DisplayFormat(DataFormatString = "{0:N0}")]
        public decimal CostSale { get; set; }

        [Display(Name = "Thông tin SP")]
        public string Information { get; set; }

        [Display(Name = "Lượt xem")]
        public Nullable<int> Views { get; set; }

        [Display(Name = "Sản phẩm hot")]
        public bool ProductHot { get; set; }

        [Display(Name = "Địa chỉ")]
        public string Address { get; set; }

        [Display(Name = "Tên shop")]
        public string ShopName { get; set; }

        [Display(Name = "Kích hoạt")]
        public bool Deleted { get; set; }

        public int UserId { get; set; }

        [Display(Name = "Ngày khởi tạo")]
        public Nullable<System.DateTime> Created { get; set; }

        [Display(Name = "Ngày hiệu chỉnh")]
        public Nullable<System.DateTime> Modified { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual User User { get; set; }
    }
}
