//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace muachung.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public User()
        {
            this.Products = new HashSet<Product>();
            this.Adverts = new HashSet<Advert>();
        }
    
        public int UserId { get; set; }

        [Display(Name = "Tên tài khoản")]
        public string Username { get; set; }

        [Display(Name = "Mật khẩu")]
        public string Password { get; set; }

        [Display(Name = "Kích hoạt")]
        public bool Active { get; set; }

        [Display(Name = "Hình đại diện")]
        public string Avatar { get; set; }

        public bool RememberMe { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Advert> Adverts { get; set; }
    }
}
